apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
spec:
  replicas: 2
  selector:
    matchLabels: # labels to select/identify the deployment
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec: # pod spec
      containers:
        - name: hello-world
          image: hello-world-image:latest # image we pushed
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-deployment
  namespace: mule-apis
spec:
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: hello-world
  type: ClusterIP
